// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day63MyProj.Data.Models
{
    public partial class User
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Pan { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Gender { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MobileNumber { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "text")]
        public string Comments { get; set; }
        public int DepartmentRefId { get; set; }
        public Department DepartmentRef { get; set; }
    }
}